project_id = "rmjonykhawkelzdykbzb"

[functions.facebook-followers]
verify_jwt = false

[functions.facebook-posts]
verify_jwt = false

[functions.facebook-stats]
verify_jwt = false

[functions.instagram-stats]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.submit-survey]
verify_jwt = false
